version: "3"

services:
  frontend:
    container_name: "frontend"
    depends_on:
      - backend
    build: ./frontend/
    ports:
      - "80:80"
      - "443:443"
  backend:
    container_name: "backend"
    build: ./backend/
    ports:
      - "8080:8080"